import { Module } from "./types";

export const availableModules: Module[] = [
  {
    id: "zk-email",
    name: "zk-email",
    description: "Verify email ownership",
    icon: "Email",
    status: "active",
    config: {
      type: "selection",
      label: "Provider",
      options: ["Gmail", "Outlook", "Any"],
      default: "Any",
    },
  },
  {
    id: "zk-age",
    name: "zk-age",
    description: "ZK proof of age (Noir circuit)",
    icon: "User",
    status: "active",
    config: {
      type: "threshold",
      label: "Minimum Age",
      min: 13,
      max: 100,
      default: 18,
    },
  },
  {
    id: "zk-github",
    name: "zk-github",
    description: "Verify GitHub account",
    icon: "Github",
    status: "active",
    config: {
      type: "threshold",
      label: "Min Commits",
      min: 0,
      max: 10000,
      default: 10,
    },
  },
  {
    id: "zk-twitter",
    name: "zk-twitter",
    description: "Verify Twitter/X account",
    icon: "Twitter",
    status: "active",
    config: {
      type: "selection",
      label: "Verification",
      options: ["Account", "Followers", "Verified"],
      default: "Account",
    },
  },
  {
    id: "zk-balance",
    name: "zk-balance",
    description: "ZK proof of balance threshold",
    icon: "Bank",
    status: "active",
    config: {
      type: "threshold",
      label: "Min Balance (ETH)",
      min: 0,
      max: 1000,
      default: 1,
    },
  },
  {
    id: "zk-chain-balance",
    name: "zk-chain-balance",
    description: "Cross-chain balance via Flare",
    icon: "Chains",
    status: "coming",
    config: {
      type: "selection",
      label: "Source Chain",
      options: ["Ethereum", "BNB Chain", "XRP", "Dogecoin", "Litecoin", "Flare", "Mantle"],
      default: "Ethereum",
    },
  },
  {
    id: "zk-aadhar",
    name: "zk-aadhar",
    description: "Verify Aadhaar identity",
    icon: "IdCard",
    status: "coming",
  },
  {
    id: "zk-amazon",
    name: "zk-amazon",
    description: "Verify Amazon account",
    icon: "Amazon",
    status: "coming",
    config: {
      type: "selection",
      label: "Verification",
      options: ["Prime Member", "Purchase History", "Address"],
      default: "Prime Member",
    },
  },
  {
    id: "zk-country",
    name: "zk-country",
    description: "Verify country/region",
    icon: "Globe",
    status: "coming",
    config: {
      type: "selection",
      label: "Region",
      options: ["US", "EU", "APAC", "Custom"],
      default: "US",
    },
  },
  {
    id: "zk-kyc",
    name: "zk-kyc",
    description: "Verify KYC status",
    icon: "Shield",
    status: "coming",
    config: {
      type: "selection",
      label: "Provider",
      options: ["Jumio", "Onfido", "Persona", "Any"],
      default: "Any",
    },
  },
];
