import { Module } from "./types";

export const availableModules: Module[] = [
  {
    id: "zk-email",
    name: "zk-email",
    description: "Verify email ownership",
    icon: "Email",
    status: "active",
    gradient: "from-blue-500 to-cyan-500",
    config: {
      type: "selection",
      label: "Provider",
      options: ["Gmail", "Outlook", "Any"],
      default: "Any",
    },
  },
  {
    id: "zk-age",
    name: "zk-age",
    description: "Verify age threshold",
    icon: "User",
    status: "active",
    gradient: "from-purple-500 to-pink-500",
    config: {
      type: "threshold",
      label: "Minimum Age",
      min: 13,
      max: 100,
      default: 18,
    },
  },
  {
    id: "zk-github",
    name: "zk-github",
    description: "Verify GitHub account",
    icon: "Github",
    status: "active",
    gradient: "from-gray-700 to-gray-900",
    config: {
      type: "threshold",
      label: "Min Commits",
      min: 0,
      max: 10000,
      default: 10,
    },
  },
  {
    id: "zk-bank-balance",
    name: "zk-bank-balance",
    description: "Verify bank balance",
    icon: "Bank",
    status: "coming",
    gradient: "from-green-500 to-emerald-500",
    config: {
      type: "threshold",
      label: "Min Balance ($)",
      min: 0,
      max: 1000000,
      default: 1000,
    },
  },
  {
    id: "zk-aadhar",
    name: "zk-aadhar",
    description: "Verify Aadhaar identity",
    icon: "IdCard",
    status: "coming",
    gradient: "from-indigo-500 to-violet-500",
  },
  {
    id: "zk-amazon",
    name: "zk-amazon",
    description: "Verify Amazon account",
    icon: "Amazon",
    status: "coming",
    gradient: "from-orange-500 to-amber-500",
    config: {
      type: "selection",
      label: "Verification",
      options: ["Prime Member", "Purchase History", "Address"],
      default: "Prime Member",
    },
  },
  {
    id: "zk-country",
    name: "zk-country",
    description: "Verify country/region",
    icon: "Globe",
    status: "coming",
    gradient: "from-teal-500 to-cyan-500",
    config: {
      type: "selection",
      label: "Region",
      options: ["US", "EU", "APAC", "Custom"],
      default: "US",
    },
  },
  {
    id: "zk-kyc",
    name: "zk-kyc",
    description: "Verify KYC status",
    icon: "Shield",
    status: "coming",
    gradient: "from-rose-500 to-red-500",
    config: {
      type: "selection",
      label: "Provider",
      options: ["Jumio", "Onfido", "Persona", "Any"],
      default: "Any",
    },
  },
];
