// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "../interfaces/IUntracedModule.sol";

/**
 * @title ZKAgeVerifier
 * @notice On-chain verifier for ZK age proofs generated by Noir circuits
 * @dev Integrates with UltraPlonk verifier for Noir proofs
 */
contract ZKAgeVerifier is IUntracedModule {
    /// @notice Attribute type for ZK age verification
    bytes32 public constant ATTRIBUTE_TYPE = keccak256("ZK_AGE");

    /// @notice The registry contract address
    address public immutable registry;

    /// @notice The UltraPlonk verifier contract (generated by Noir/bb)
    address public verifierContract;

    /// @notice Owner for updating verifier
    address public owner;

    /// @notice Mapping of commitment => user => verified
    mapping(bytes32 => mapping(address => bool)) public verifiedCommitments;

    /// @notice Mapping of user => last verified min age
    mapping(address => uint8) public userMinAgeVerified;

    /// @notice Event emitted when age is verified
    event AgeVerified(
        address indexed user,
        uint8 minAge,
        bytes32 commitment,
        uint256 timestamp
    );

    /// @notice Event emitted when verifier contract is updated
    event VerifierUpdated(address oldVerifier, address newVerifier);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    /**
     * @param _registry The UntracedRegistry contract address
     */
    constructor(address _registry) {
        registry = _registry;
        owner = msg.sender;
    }

    /**
     * @notice Set the UltraPlonk verifier contract address
     * @param _verifier The verifier contract address (generated by bb)
     */
    function setVerifierContract(address _verifier) external onlyOwner {
        address oldVerifier = verifierContract;
        verifierContract = _verifier;
        emit VerifierUpdated(oldVerifier, _verifier);
    }

    /**
     * @notice Verify a ZK age proof
     * @param proof The proof bytes from Noir prover
     * @param publicInputs The public inputs: [currentYear, currentMonth, currentDay, minAge, userAddress, commitment]
     * @return valid Whether the proof is valid
     */
    function verifyAgeProof(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external returns (bool valid) {
        require(verifierContract != address(0), "Verifier not set");
        require(publicInputs.length == 6, "Invalid public inputs length");

        // Extract public inputs
        uint32 currentYear = uint32(uint256(publicInputs[0]));
        uint8 currentMonth = uint8(uint256(publicInputs[1]));
        uint8 currentDay = uint8(uint256(publicInputs[2]));
        uint8 minAge = uint8(uint256(publicInputs[3]));
        address userAddress = address(uint160(uint256(publicInputs[4])));
        bytes32 commitment = publicInputs[5];

        // Verify current date is reasonable (within last day)
        // This prevents using old proofs
        require(isRecentDate(currentYear, currentMonth, currentDay), "Stale proof");

        // Call the UltraPlonk verifier
        // Note: The actual call format depends on the generated verifier
        (bool success, bytes memory result) = verifierContract.staticcall(
            abi.encodeWithSignature("verify(bytes,bytes32[])", proof, publicInputs)
        );

        require(success && abi.decode(result, (bool)), "Proof verification failed");

        // Store verification result
        verifiedCommitments[commitment][userAddress] = true;
        userMinAgeVerified[userAddress] = minAge;

        emit AgeVerified(userAddress, minAge, commitment, block.timestamp);

        return true;
    }

    /**
     * @notice Check if a user has verified their age
     * @param user The user address
     * @param requiredAge The minimum age to check
     */
    function hasVerifiedAge(address user, uint8 requiredAge) external view returns (bool) {
        return userMinAgeVerified[user] >= requiredAge;
    }

    /**
     * @inheritdoc IUntracedModule
     */
    function verify(bytes calldata proof) external view returns (bool) {
        // For basic module interface compatibility
        // Full verification should use verifyAgeProof
        return proof.length > 0;
    }

    /**
     * @inheritdoc IUntracedModule
     */
    function attributeType() external pure returns (bytes32) {
        return ATTRIBUTE_TYPE;
    }

    /**
     * @inheritdoc IUntracedModule
     */
    function moduleName() external pure returns (string memory) {
        return "zk-age";
    }

    /**
     * @dev Check if the date is within acceptable range (last 24 hours)
     */
    function isRecentDate(
        uint32 year,
        uint8 month,
        uint8 day
    ) internal view returns (bool) {
        // Simple check: year should be current or previous year
        // In production, implement proper date comparison
        uint256 currentTimestamp = block.timestamp;
        uint256 currentYear = 1970 + (currentTimestamp / 365 days);

        return year >= currentYear - 1 && year <= currentYear + 1;
    }

    /**
     * @notice Transfer ownership
     */
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Invalid address");
        owner = newOwner;
    }
}
