// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "../interfaces/IUntracedModule.sol";

/**
 * @title ZKBalanceVerifier
 * @notice On-chain verifier for ZK balance proofs generated by Noir circuits
 * @dev Integrates with UltraPlonk verifier for Noir proofs
 */
contract ZKBalanceVerifier is IUntracedModule {
    /// @notice Attribute type for ZK balance verification
    bytes32 public constant ATTRIBUTE_TYPE = keccak256("ZK_BALANCE");

    /// @notice The registry contract address
    address public immutable registry;

    /// @notice The UltraPlonk verifier contract (generated by Noir/bb)
    address public verifierContract;

    /// @notice Owner for updating verifier
    address public owner;

    /// @notice Struct to store verification details
    struct BalanceVerification {
        uint256 minBalance;
        uint256 timestamp;
        uint256 maxAgeSeconds;
        bytes32 commitment;
        bool verified;
    }

    /// @notice Mapping of user => verification details
    mapping(address => BalanceVerification) public userVerifications;

    /// @notice Event emitted when balance is verified
    event BalanceVerified(
        address indexed user,
        uint256 minBalance,
        bytes32 commitment,
        uint256 timestamp,
        uint256 expiresAt
    );

    /// @notice Event emitted when verifier contract is updated
    event VerifierUpdated(address oldVerifier, address newVerifier);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    /**
     * @param _registry The UntracedRegistry contract address
     */
    constructor(address _registry) {
        registry = _registry;
        owner = msg.sender;
    }

    /**
     * @notice Set the UltraPlonk verifier contract address
     * @param _verifier The verifier contract address
     */
    function setVerifierContract(address _verifier) external onlyOwner {
        address oldVerifier = verifierContract;
        verifierContract = _verifier;
        emit VerifierUpdated(oldVerifier, _verifier);
    }

    /**
     * @notice Verify a ZK balance proof
     * @param proof The proof bytes from Noir prover
     * @param publicInputs The public inputs: [minBalance, timestamp, maxAgeSeconds, userAddress, commitment]
     * @return valid Whether the proof is valid
     */
    function verifyBalanceProof(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external returns (bool valid) {
        require(verifierContract != address(0), "Verifier not set");
        require(publicInputs.length == 5, "Invalid public inputs length");

        // Extract public inputs
        uint256 minBalance = uint256(publicInputs[0]);
        uint256 timestamp = uint256(publicInputs[1]);
        uint256 maxAgeSeconds = uint256(publicInputs[2]);
        address userAddress = address(uint160(uint256(publicInputs[3])));
        bytes32 commitment = publicInputs[4];

        // Verify proof is not expired
        require(block.timestamp <= timestamp + maxAgeSeconds, "Proof expired");

        // Verify timestamp is not in the future
        require(timestamp <= block.timestamp + 60, "Invalid timestamp");

        // Call the UltraPlonk verifier
        (bool success, bytes memory result) = verifierContract.staticcall(
            abi.encodeWithSignature("verify(bytes,bytes32[])", proof, publicInputs)
        );

        require(success && abi.decode(result, (bool)), "Proof verification failed");

        // Store verification result
        userVerifications[userAddress] = BalanceVerification({
            minBalance: minBalance,
            timestamp: timestamp,
            maxAgeSeconds: maxAgeSeconds,
            commitment: commitment,
            verified: true
        });

        emit BalanceVerified(
            userAddress,
            minBalance,
            commitment,
            timestamp,
            timestamp + maxAgeSeconds
        );

        return true;
    }

    /**
     * @notice Check if a user has verified their balance
     * @param user The user address
     * @param requiredBalance The minimum balance to check
     */
    function hasVerifiedBalance(
        address user,
        uint256 requiredBalance
    ) external view returns (bool) {
        BalanceVerification memory v = userVerifications[user];

        // Check verification exists and is not expired
        if (!v.verified) return false;
        if (block.timestamp > v.timestamp + v.maxAgeSeconds) return false;

        // Check balance meets requirement
        return v.minBalance >= requiredBalance;
    }

    /**
     * @notice Get verification details for a user
     * @param user The user address
     */
    function getVerification(
        address user
    ) external view returns (BalanceVerification memory) {
        return userVerifications[user];
    }

    /**
     * @notice Check if verification is still valid (not expired)
     * @param user The user address
     */
    function isVerificationValid(address user) external view returns (bool) {
        BalanceVerification memory v = userVerifications[user];
        if (!v.verified) return false;
        return block.timestamp <= v.timestamp + v.maxAgeSeconds;
    }

    /**
     * @inheritdoc IUntracedModule
     */
    function verify(bytes calldata proof) external view returns (bool) {
        return proof.length > 0;
    }

    /**
     * @inheritdoc IUntracedModule
     */
    function attributeType() external pure returns (bytes32) {
        return ATTRIBUTE_TYPE;
    }

    /**
     * @inheritdoc IUntracedModule
     */
    function moduleName() external pure returns (string memory) {
        return "zk-balance";
    }

    /**
     * @notice Transfer ownership
     */
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Invalid address");
        owner = newOwner;
    }
}
