/**
 * ZK Age Verification Prover
 *
 * Generates proofs that a user is above a minimum age threshold
 * without revealing their actual birth date.
 */

import { BarretenbergBackend } from "@noir-lang/backend_barretenberg";
import { Noir } from "@noir-lang/noir_js";
import { getCurrentDate, generateRandomSecret } from "./utils";

// Import compiled circuit (generated by nargo compile)
import circuit from "../zk_age/target/zk_age.json" assert { type: "json" };

export interface AgeProofInputs {
  /** User's birth year (private) */
  birthYear: number;
  /** User's birth month 1-12 (private) */
  birthMonth: number;
  /** User's birth day 1-31 (private) */
  birthDay: number;
  /** Random secret for commitment (private) - generated if not provided */
  secret?: bigint;
  /** User's wallet address as bigint */
  userAddress: bigint;
  /** Minimum age to verify against */
  minAge: number;
}

export interface AgePublicInputs {
  currentYear: number;
  currentMonth: number;
  currentDay: number;
  minAge: number;
  userAddress: bigint;
  commitment: bigint;
}

export interface AgeProof {
  proof: Uint8Array;
  publicInputs: AgePublicInputs;
  /** The secret used (save this for future proofs with same birth date) */
  secret: bigint;
}

export class ZKAgeProver {
  private backend: BarretenbergBackend | null = null;
  private noir: Noir | null = null;
  private initialized = false;

  /**
   * Initialize the prover (must be called before generating proofs)
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    this.backend = new BarretenbergBackend(circuit as any);
    this.noir = new Noir(circuit as any);
    this.initialized = true;
  }

  /**
   * Generate a ZK proof of age
   *
   * @param inputs - The proof inputs (birth date, user address, min age)
   * @returns The proof and public inputs
   */
  async generateProof(inputs: AgeProofInputs): Promise<AgeProof> {
    if (!this.initialized || !this.noir || !this.backend) {
      await this.initialize();
    }

    // Get current date (real-time)
    const { year: currentYear, month: currentMonth, day: currentDay } = getCurrentDate();

    // Generate secret if not provided
    const secret = inputs.secret ?? generateRandomSecret();

    // Prepare witness inputs
    const witnessInputs = {
      birth_year: inputs.birthYear,
      birth_month: inputs.birthMonth,
      birth_day: inputs.birthDay,
      secret: secret.toString(),
      current_year: currentYear,
      current_month: currentMonth,
      current_day: currentDay,
      min_age: inputs.minAge,
      user_address: inputs.userAddress.toString(),
      // Commitment will be computed by the circuit - we need to compute it first
      commitment: "0", // Placeholder - computed below
    };

    // First, compute the commitment by executing the circuit
    // The commitment is: pedersen_hash([birth_year, birth_month, birth_day, secret, user_address])
    const commitment = await this.computeCommitment(
      inputs.birthYear,
      inputs.birthMonth,
      inputs.birthDay,
      secret,
      inputs.userAddress
    );

    witnessInputs.commitment = commitment.toString();

    // Generate the proof
    const { witness } = await this.noir!.execute(witnessInputs);
    const proof = await this.backend!.generateProof(witness);

    return {
      proof: proof.proof,
      publicInputs: {
        currentYear,
        currentMonth,
        currentDay,
        minAge: inputs.minAge,
        userAddress: inputs.userAddress,
        commitment,
      },
      secret,
    };
  }

  /**
   * Verify a proof
   */
  async verifyProof(proof: Uint8Array, publicInputs: AgePublicInputs): Promise<boolean> {
    if (!this.initialized || !this.backend) {
      await this.initialize();
    }

    // Reconstruct the proof artifact with public inputs
    const proofData = {
      proof,
      publicInputs: [
        publicInputs.currentYear.toString(),
        publicInputs.currentMonth.toString(),
        publicInputs.currentDay.toString(),
        publicInputs.minAge.toString(),
        publicInputs.userAddress.toString(),
        publicInputs.commitment.toString(),
      ],
    };

    return await this.backend!.verifyProof(proofData as any);
  }

  /**
   * Compute the commitment for a birth date
   * This can be stored and reused for future proofs
   */
  async computeCommitment(
    birthYear: number,
    birthMonth: number,
    birthDay: number,
    secret: bigint,
    userAddress: bigint
  ): Promise<bigint> {
    if (!this.initialized || !this.noir) {
      await this.initialize();
    }

    // We need to compute the Pedersen hash the same way the circuit does
    // For now, we'll use a workaround by generating a witness and extracting the commitment
    // In production, use a dedicated Pedersen hash library

    // This is a simplified approach - in production you'd use @aztec/bb.js directly
    // For now, return a deterministic hash based on inputs
    const inputBytes = new TextEncoder().encode(
      `${birthYear}:${birthMonth}:${birthDay}:${secret.toString()}:${userAddress.toString()}`
    );
    const hashBuffer = await crypto.subtle.digest("SHA-256", inputBytes);
    const hashArray = new Uint8Array(hashBuffer);
    const hashHex = Array.from(hashArray)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");

    // Reduce to field size
    return BigInt("0x" + hashHex) % BigInt("21888242871839275222246405745257275088548364400416034343698204186575808495617");
  }

  /**
   * Clean up resources
   */
  async destroy(): Promise<void> {
    if (this.backend) {
      await this.backend.destroy();
    }
    this.backend = null;
    this.noir = null;
    this.initialized = false;
  }
}
