/**
 * ZK Age Verification Prover
 *
 * Generates proofs that a user is above a minimum age threshold
 * without revealing their actual birth date.
 */

import { UltraHonkBackend } from "@aztec/bb.js";
import { Noir } from "@noir-lang/noir_js";
import {
  getCurrentDate,
  generateRandomSecret,
  computeAgeCommitment,
  addressToField,
} from "./utils.js";

// Import compiled circuit (generated by nargo compile)
import circuit from "../zk_age/target/zk_age.json" with { type: "json" };

export interface AgeProofInputs {
  /** User's birth year (private) */
  birthYear: number;
  /** User's birth month 1-12 (private) */
  birthMonth: number;
  /** User's birth day 1-31 (private) */
  birthDay: number;
  /** Random secret for commitment (private) - generated if not provided */
  secret?: bigint;
  /** User's wallet address (hex string or bigint) */
  userAddress: string | bigint;
  /** Minimum age to verify against */
  minAge: number;
}

export interface AgePublicInputs {
  currentYear: number;
  currentMonth: number;
  currentDay: number;
  minAge: number;
  userAddress: bigint;
  commitment: bigint;
}

export interface AgeProof {
  /** The ZK proof bytes */
  proof: Uint8Array;
  /** Public inputs that were verified */
  publicInputs: AgePublicInputs;
  /** The secret used (save this for future proofs with same birth date) */
  secret: bigint;
}

export class ZKAgeProver {
  private backend: UltraHonkBackend | null = null;
  private noir: Noir | null = null;
  private initialized = false;

  /**
   * Initialize the prover (must be called before generating proofs)
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    // Initialize Noir for witness generation
    this.noir = new Noir(circuit as any);

    // Initialize UltraHonk backend for proof generation
    this.backend = new UltraHonkBackend((circuit as any).bytecode);

    this.initialized = true;
  }

  /**
   * Generate a ZK proof of age
   *
   * @param inputs - The proof inputs (birth date, user address, min age)
   * @returns The proof and public inputs
   */
  async generateProof(inputs: AgeProofInputs): Promise<AgeProof> {
    if (!this.initialized || !this.noir || !this.backend) {
      await this.initialize();
    }

    // Get current date (real-time)
    const { year: currentYear, month: currentMonth, day: currentDay } = getCurrentDate();

    // Generate secret if not provided
    const secret = inputs.secret ?? generateRandomSecret();

    // Convert user address to field element
    const userAddressBigInt =
      typeof inputs.userAddress === "string"
        ? addressToField(inputs.userAddress)
        : inputs.userAddress;

    // Compute the commitment using Barretenberg's Pedersen hash
    const commitment = await computeAgeCommitment(
      inputs.birthYear,
      inputs.birthMonth,
      inputs.birthDay,
      secret,
      userAddressBigInt
    );

    // Prepare witness inputs for Noir circuit
    const witnessInputs = {
      birth_year: inputs.birthYear,
      birth_month: inputs.birthMonth,
      birth_day: inputs.birthDay,
      secret: secret.toString(),
      current_year: currentYear,
      current_month: currentMonth,
      current_day: currentDay,
      min_age: inputs.minAge,
      user_address: userAddressBigInt.toString(),
      commitment: commitment.toString(),
    };

    // Execute circuit to generate witness
    const { witness } = await this.noir!.execute(witnessInputs);

    // Generate the proof using UltraHonk
    const proof = await this.backend!.generateProof(witness);

    return {
      proof: proof.proof,
      publicInputs: {
        currentYear,
        currentMonth,
        currentDay,
        minAge: inputs.minAge,
        userAddress: userAddressBigInt,
        commitment,
      },
      secret,
    };
  }

  /**
   * Verify a proof
   */
  async verifyProof(proof: AgeProof): Promise<boolean> {
    if (!this.initialized || !this.backend) {
      await this.initialize();
    }

    // Reconstruct the proof artifact
    const proofData = {
      proof: proof.proof,
      publicInputs: [
        proof.publicInputs.currentYear.toString(),
        proof.publicInputs.currentMonth.toString(),
        proof.publicInputs.currentDay.toString(),
        proof.publicInputs.minAge.toString(),
        proof.publicInputs.userAddress.toString(),
        proof.publicInputs.commitment.toString(),
      ],
    };

    return await this.backend!.verifyProof(proofData as any);
  }

  /**
   * Compute the commitment for a birth date
   * This can be stored and reused for future proofs
   */
  async computeCommitment(
    birthYear: number,
    birthMonth: number,
    birthDay: number,
    secret: bigint,
    userAddress: string | bigint
  ): Promise<bigint> {
    const userAddressBigInt =
      typeof userAddress === "string" ? addressToField(userAddress) : userAddress;

    return computeAgeCommitment(birthYear, birthMonth, birthDay, secret, userAddressBigInt);
  }

  /**
   * Clean up resources
   */
  async destroy(): Promise<void> {
    if (this.backend) {
      await this.backend.destroy();
    }
    this.backend = null;
    this.noir = null;
    this.initialized = false;
  }
}
