/**
 * ZK Balance Verification Prover
 *
 * Generates proofs that a user has a balance above a threshold
 * without revealing the exact amount.
 */

import { UltraHonkBackend } from "@aztec/bb.js";
import { Noir } from "@noir-lang/noir_js";
import {
  getCurrentTimestamp,
  generateRandomSecret,
  computeBalanceCommitment,
  addressToField,
} from "./utils.js";

// Import compiled circuit (generated by nargo compile)
import circuit from "../zk_balance/target/zk_balance.json" with { type: "json" };

export interface BalanceProofInputs {
  /** User's actual balance in smallest unit (private) */
  balance: bigint;
  /** Random secret for commitment (private) - generated if not provided */
  secret?: bigint;
  /** Additional salt for commitment (private) - generated if not provided */
  salt?: bigint;
  /** User's wallet address (hex string or bigint) */
  userAddress: string | bigint;
  /** Minimum balance threshold to verify against */
  minBalance: bigint;
  /** Maximum age of the proof in seconds (default: 1 hour) */
  maxAgeSeconds?: number;
}

export interface BalancePublicInputs {
  minBalance: bigint;
  timestamp: number;
  maxAgeSeconds: number;
  userAddress: bigint;
  balanceCommitment: bigint;
}

export interface BalanceProof {
  /** The ZK proof bytes */
  proof: Uint8Array;
  /** Public inputs that were verified */
  publicInputs: BalancePublicInputs;
  /** The secret used (save this for future proofs) */
  secret: bigint;
  /** The salt used (save this for future proofs) */
  salt: bigint;
}

export class ZKBalanceProver {
  private backend: UltraHonkBackend | null = null;
  private noir: Noir | null = null;
  private initialized = false;

  /**
   * Initialize the prover (must be called before generating proofs)
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    // Initialize Noir for witness generation
    this.noir = new Noir(circuit as any);

    // Initialize UltraHonk backend for proof generation
    this.backend = new UltraHonkBackend((circuit as any).bytecode);

    this.initialized = true;
  }

  /**
   * Generate a ZK proof of balance
   *
   * @param inputs - The proof inputs (balance, user address, min balance)
   * @returns The proof and public inputs
   */
  async generateProof(inputs: BalanceProofInputs): Promise<BalanceProof> {
    if (!this.initialized || !this.noir || !this.backend) {
      await this.initialize();
    }

    // Get current timestamp (real-time)
    const timestamp = getCurrentTimestamp();
    const maxAgeSeconds = inputs.maxAgeSeconds ?? 3600; // Default 1 hour

    // Generate secrets if not provided
    const secret = inputs.secret ?? generateRandomSecret();
    const salt = inputs.salt ?? generateRandomSecret();

    // Convert user address to field element
    const userAddressBigInt =
      typeof inputs.userAddress === "string"
        ? addressToField(inputs.userAddress)
        : inputs.userAddress;

    // Compute the commitment using Barretenberg's Pedersen hash
    const balanceCommitment = await computeBalanceCommitment(
      inputs.balance,
      secret,
      salt,
      userAddressBigInt
    );

    // Prepare witness inputs for Noir circuit
    const witnessInputs = {
      balance: inputs.balance.toString(),
      secret: secret.toString(),
      salt: salt.toString(),
      min_balance: inputs.minBalance.toString(),
      timestamp: timestamp.toString(),
      max_age_seconds: maxAgeSeconds.toString(),
      user_address: userAddressBigInt.toString(),
      balance_commitment: balanceCommitment.toString(),
    };

    // Execute circuit to generate witness
    const { witness } = await this.noir!.execute(witnessInputs);

    // Generate the proof using UltraHonk
    const proof = await this.backend!.generateProof(witness);

    return {
      proof: proof.proof,
      publicInputs: {
        minBalance: inputs.minBalance,
        timestamp,
        maxAgeSeconds,
        userAddress: userAddressBigInt,
        balanceCommitment,
      },
      secret,
      salt,
    };
  }

  /**
   * Verify a proof
   */
  async verifyProof(proof: BalanceProof): Promise<boolean> {
    if (!this.initialized || !this.backend) {
      await this.initialize();
    }

    // Reconstruct the proof artifact
    const proofData = {
      proof: proof.proof,
      publicInputs: [
        proof.publicInputs.minBalance.toString(),
        proof.publicInputs.timestamp.toString(),
        proof.publicInputs.maxAgeSeconds.toString(),
        proof.publicInputs.userAddress.toString(),
        proof.publicInputs.balanceCommitment.toString(),
      ],
    };

    return await this.backend!.verifyProof(proofData as any);
  }

  /**
   * Compute the commitment for a balance
   * This can be stored and reused for future proofs
   */
  async computeCommitment(
    balance: bigint,
    secret: bigint,
    salt: bigint,
    userAddress: string | bigint
  ): Promise<bigint> {
    const userAddressBigInt =
      typeof userAddress === "string" ? addressToField(userAddress) : userAddress;

    return computeBalanceCommitment(balance, secret, salt, userAddressBigInt);
  }

  /**
   * Clean up resources
   */
  async destroy(): Promise<void> {
    if (this.backend) {
      await this.backend.destroy();
    }
    this.backend = null;
    this.noir = null;
    this.initialized = false;
  }
}
