/**
 * ZK Balance Verification Prover
 *
 * Generates proofs that a user has a balance above a threshold
 * without revealing the exact amount.
 */

import { BarretenbergBackend } from "@noir-lang/backend_barretenberg";
import { Noir } from "@noir-lang/noir_js";
import { getCurrentTimestamp, generateRandomSecret } from "./utils";

// Import compiled circuit (generated by nargo compile)
import circuit from "../zk_balance/target/zk_balance.json" assert { type: "json" };

export interface BalanceProofInputs {
  /** User's actual balance in smallest unit (private) */
  balance: bigint;
  /** Random secret for commitment (private) - generated if not provided */
  secret?: bigint;
  /** Additional salt for commitment (private) - generated if not provided */
  salt?: bigint;
  /** User's wallet address as bigint */
  userAddress: bigint;
  /** Minimum balance threshold to verify against */
  minBalance: bigint;
  /** Maximum age of the proof in seconds (default: 1 hour) */
  maxAgeSeconds?: number;
}

export interface BalancePublicInputs {
  minBalance: bigint;
  timestamp: number;
  maxAgeSeconds: number;
  userAddress: bigint;
  balanceCommitment: bigint;
}

export interface BalanceProof {
  proof: Uint8Array;
  publicInputs: BalancePublicInputs;
  /** The secret used (save this for future proofs) */
  secret: bigint;
  /** The salt used (save this for future proofs) */
  salt: bigint;
}

export class ZKBalanceProver {
  private backend: BarretenbergBackend | null = null;
  private noir: Noir | null = null;
  private initialized = false;

  /**
   * Initialize the prover (must be called before generating proofs)
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;

    this.backend = new BarretenbergBackend(circuit as any);
    this.noir = new Noir(circuit as any);
    this.initialized = true;
  }

  /**
   * Generate a ZK proof of balance
   *
   * @param inputs - The proof inputs (balance, user address, min balance)
   * @returns The proof and public inputs
   */
  async generateProof(inputs: BalanceProofInputs): Promise<BalanceProof> {
    if (!this.initialized || !this.noir || !this.backend) {
      await this.initialize();
    }

    // Get current timestamp (real-time)
    const timestamp = getCurrentTimestamp();
    const maxAgeSeconds = inputs.maxAgeSeconds ?? 3600; // Default 1 hour

    // Generate secrets if not provided
    const secret = inputs.secret ?? generateRandomSecret();
    const salt = inputs.salt ?? generateRandomSecret();

    // Compute the commitment
    const balanceCommitment = await this.computeCommitment(
      inputs.balance,
      secret,
      salt,
      inputs.userAddress
    );

    // Prepare witness inputs
    const witnessInputs = {
      balance: inputs.balance.toString(),
      secret: secret.toString(),
      salt: salt.toString(),
      min_balance: inputs.minBalance.toString(),
      timestamp: timestamp.toString(),
      max_age_seconds: maxAgeSeconds.toString(),
      user_address: inputs.userAddress.toString(),
      balance_commitment: balanceCommitment.toString(),
    };

    // Generate the proof
    const { witness } = await this.noir!.execute(witnessInputs);
    const proof = await this.backend!.generateProof(witness);

    return {
      proof: proof.proof,
      publicInputs: {
        minBalance: inputs.minBalance,
        timestamp,
        maxAgeSeconds,
        userAddress: inputs.userAddress,
        balanceCommitment,
      },
      secret,
      salt,
    };
  }

  /**
   * Verify a proof
   */
  async verifyProof(proof: Uint8Array, publicInputs: BalancePublicInputs): Promise<boolean> {
    if (!this.initialized || !this.backend) {
      await this.initialize();
    }

    // Reconstruct the proof artifact with public inputs
    const proofData = {
      proof,
      publicInputs: [
        publicInputs.minBalance.toString(),
        publicInputs.timestamp.toString(),
        publicInputs.maxAgeSeconds.toString(),
        publicInputs.userAddress.toString(),
        publicInputs.balanceCommitment.toString(),
      ],
    };

    return await this.backend!.verifyProof(proofData as any);
  }

  /**
   * Compute the commitment for a balance
   * This can be stored and reused for future proofs
   */
  async computeCommitment(
    balance: bigint,
    secret: bigint,
    salt: bigint,
    userAddress: bigint
  ): Promise<bigint> {
    if (!this.initialized || !this.noir) {
      await this.initialize();
    }

    // Compute Pedersen hash the same way the circuit does
    // Simplified approach using SHA-256 as placeholder
    const inputBytes = new TextEncoder().encode(
      `${balance.toString()}:${secret.toString()}:${salt.toString()}:${userAddress.toString()}`
    );
    const hashBuffer = await crypto.subtle.digest("SHA-256", inputBytes);
    const hashArray = new Uint8Array(hashBuffer);
    const hashHex = Array.from(hashArray)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");

    // Reduce to field size
    return BigInt("0x" + hashHex) % BigInt("21888242871839275222246405745257275088548364400416034343698204186575808495617");
  }

  /**
   * Clean up resources
   */
  async destroy(): Promise<void> {
    if (this.backend) {
      await this.backend.destroy();
    }
    this.backend = null;
    this.noir = null;
    this.initialized = false;
  }
}
